// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdqolplrdwwxdbnlgize.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcW9scGxyZHd3eGRibmxnaXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDgxNzUsImV4cCI6MjA2MTc4NDE3NX0.NKfhlpfZgrWw5O53DqSvvpr43xgTJyryt4pqCk_bwKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});